### ISSUE TITLE
Flag are not languages

### ISSUE THREAD

**Issue by bartclaeys** [usrz/bootstrap-languages#10]
It's probably a long stretch but... flags are not languages. You should avoid flags for languages at all times.

http://flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/

**Comment by marcelstoer** [comment]
I agree but what makes that an issue for this project?

If you don't want to show the flag then just use 

```html
<span class="lang-lbl" lang="en"></span>
```
rather than
```html
<span class="lang-sm lang-lbl" lang="en"></span>
```

I don't want to start a heated debate here but *if* you choose to display flags the flag should represent the country in which the language originated. That's why showing the US flag for English is so wrong (see #7).

**Comment by bc173** [comment]
@marcelstoer I think you're starting a debate... It's hard to tell where a language originates from, or if you follow your rule, most languages originate from Europe (Spanish, French, Dutch). Plus people might not be familiar with that flag depending on the target audience (American Latinos having to choose a Spanish flag for Spanish). Summarized, flags are an extremely bad idea for a language selector.

**Comment by marcelstoer** [comment]
> Summarized, flags are an extremely bad idea for a language selector.

I agree...as said before. This project offers to display flags *if you like them* and that's fine.

**Comment by pfumagalli** [comment]
Closing this, agreed, don't use flags if you don't want to...
